/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UrlDispatcher': EventHandler<{ url: string }, { topic: 'google.index'; data: { url: string; retryCount?: number } } | { topic: 'indexnow.index'; data: { url: string; retryCount?: number } }>
    'SubmitUrls': ApiRouteHandler<{ urls: Array<string> }, unknown, { topic: 'url.submitted'; data: { url: string } }>
    'RetryHandler': EventHandler<{ url: string; service: 'google' | 'indexnow'; retryCount: number }, { topic: 'google.index'; data: { url: string; retryCount?: number } } | { topic: 'indexnow.index'; data: { url: string; retryCount?: number } }>
    'QuotaResetCron': CronHandler<{ topic: 'google.index'; data: { url: string; retryCount?: number } }>
    'IndexNowSubmitter': EventHandler<{ url: string; retryCount?: number }, { topic: 'submission.retry'; data: { url: string; service: 'google' | 'indexnow'; retryCount: number } }>
    'GoogleIndexer': EventHandler<{ url: string; retryCount?: number }, { topic: 'submission.retry'; data: { url: string; service: 'google' | 'indexnow'; retryCount: number } }>
    'GetStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetHistory': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}